# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2odev-nginx
  namespace: a2odev-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2odev-nginx
  template:
    metadata:
      labels:
        app: a2odev-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - nginx
            - -t
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: a2odev-ws
  namespace: a2odev-company
spec:
  ports:
  - port: 80
  selector:
    app: a2odev-nginx
  type: ClusterIP
