# hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: a2odev-nginx-hpa
  namespace: a2odev-company
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: a2odev-nginx
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 32
